
- name: Download Prometheus
  get_url:
     url: "{{ prom_url }}"
     dest: /home/kale/prometheus.tar.gz

- name: Download Grafana
  get_url:
     url: "{{ grafana_url }}"
     dest: /home/kale/grafana.tar.gz
- name: Install Prometheus
  shell: "tar zxvf /home/kale/prometheus.tar.gz"

- name: Install Grafana
  shell: "tar zxvf /home/kale/grafana.tar.gz"



- name: Create Prometheus service
  template:
    src: prometheus_service.j2
    dest: /etc/systemd/system/prometheus.service
    mode: '0644'

- name: Copy template of yml
  template:
    src: prometheus.yml
    dest: /etc/prometheus/prometheus.yml


      #- name: User creation
      # shell: useradd -rs /bin/false prometheus

- name: Owner change
  shell: chown -R prometheus:prometheus /usr/local/bin/prometheus
  shell: chown -R prometheus:prometheus /etc/prometheus

- name: Reload Prometheus
  systemd:
    name: prometheus.service
    daemon_reload: yes
    enabled: yes
    state: restarted
