[Unit]
Description=Prometheus Server
After=network.target

[Service]
User=prometheus
Group=prometheus
Type=simple
Restart=on-failure
ExecStart=/usr/local/bin/prometheus \
 --config.file  /etc/prometheus/prometheus.yml \
 --storage.tsdb.path /etc/prometheus/data

[Install]
WantedBy=multi-user.target

